apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redis-0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  
